<?php

$f="/home/groups/f/fr/freesteam/htdocs".$_SERVER['PHP_SELF'];
$t=filemtime($f);

header("Last-Modified: " . gmdate("D, d M Y H:i:s",$t) . " GMT");

?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<HTML>
<HEAD>
<TITLE>Steam Properties: diagrams generated by freesteam</TITLE>
<META NAME="Author" CONTENT="John Pye">
<META NAME="Keywords" CONTENT="Steam Properties, Water and Steam Properties, Steam Tables, IAPWS, Saturated Steam, Superheated Steam">
<META NAME="Description" CONTENT="Some diagrams drawn from the IAPWS water and steam properties correlations">
<LINK type="stylesheet=" 

<link rel="stylesheet" media="screen" href="../freesteam.css"
 type="text/css">

<style type="text/css">
h2 {margin-top:20}
</style>
	
</HEAD>
<BODY>

<h1>Steam Properties</h1>

<table><tr><td valign=top>
<div class="nav" style="margin-bottom:100%">
<a href="..">Back to freesteam home</a>

<p>Quick Links

<ul>
  <li><a t="Project Page" href="http://sf.net/projects/freesteam">SourceForge</a></li>
  <li><a title="File releases at SourceForge"
 href="http://sourceforge.net/project/showfiles.php?group_id=120898">Download</a></li>
</ul>
</div>
</td><td valign=top>

<h2>Property Diagrams</h2>

<p>Here are some diagrams generated by the <a href="..">freesteam IAPWS-IF97 steam properties library</a>, which show the location of the saturation regions for steam when plotted against various properties. I found these very useful when writing the 'whichRegion' routines for the general-purpose <a href="http://freesteam.sourceforge.net/docs/class_solver2.html">two-way property solvers</a> in freesteam.</p>

<p>You can easily reproduce these plots from <b>freesteam</b> if you use the <tt>diagram.cli</tt> program which can be generated from <tt>diagram.cli.cpp</tt> in the <a href="http://freesteam.svn.sourceforge.net/viewvc/freesteam/trunk/cli/"><tt>cli</tt> directory</a> of the freesteam source code distribution. This output of this program is a Matlab m-file which you can run. For example,

<pre>
cd cli
make diagram.cli
./diagram.cli Ts > Ts.m
</pre>

<p>Then, in Matlab, run the Ts.m m-file and you will see a T-s diagram similar to that shown below. If viewing on screen, it is recommended that you use the <tt>colordef black</tt> command before you run the M-file.</p>

<p>For all these plots, pressure is in MPa, temperature is in Kelvin, specific enthalpy and internal energy are in kJ/kg
and specific entropy is in kJ/kgK. In some cases you will notice that lines don't meet up; mostly this is due to linearly-space values being plotted on logarithmic curves, and is something we will need to fix in a future version.</p>

<?php

$plots=array(
	"T-s"=>"Temperature versus specific entropy"
	,"T-h"=>"Temperature versus specific enthalpy"
	,"T-v"=>"Temperature versus specific volume"
	,"T-p"=>"Temperature versus pressure"
	,"p-h"=>"Pressure versus specific enthalpy"
	,"p-u"=>"Pressure versus specific internal energy"
	,"p-s"=>"Temperature versus specific entropy"
	,"v-u"=>"Specific volume version specific internal energy"
);

foreach($plots as $f=>$n){
	print("<h2>$f: $n</h2>\n\n<img src=\"img/$f.png\" width=560 height=420 alt=\"$f diagram\">\n\n");
}
?>

</td></tr><table>

<hr>
<address>
John Pye<br>
Last modified: <?php print(date("j M Y",$t)) ?>
</address>

</BODY>
</HTML>
