#!/usr/bin/env python

env = Environment()

srcs = ["region1.c", "region2.c", "region3.c", "region4.c", "steam_ph.c"
	,"steam.c", "backwards.c","b23.c"
]

env.Append(CFLAGS=['-Wall'])

env.SharedLibrary("freesteam",srcs,LIBS=['m'])

env.SConscript(["python/SConscript"],'env')

env.Program("test","test.c",LINKFLAGS=['-Wl,-rpath,'+str(Dir('#'))],LIBS=['freesteam'],LIBPATH=['#'])

