import SCons.Util
import sys, os.path, platform

if platform.system()=="Windows":
	tools = ['mingw']
else:
	tools = ['default']

env = Environment(tools=tools)

prefix = "/usr"

if platform.system()=="Windows":
	if SCons.Util.can_read_reg:
		# we attempt to read the freesteam install location from the registry
		# in place of all this, you can just set the value of 'prefix' above,
		# and delete this 'if' statement.
		try:
			k = SCons.Util.RegOpenKeyEx(
					SCons.Util.hkey_mod.HKEY_LOCAL_MACHINE
					,'SOFTWARE\\freesteam'
				)
			val, tok = SCons.Util.RegQueryValueEx(k,"Install_Dir")

			if os.path.exists(val):
				print "FOUND FREESTEAM INSTALLED",val
				prefix = val
			else:
				print "FREESTEAM NOT FOUND AT EXPECTED LOCATION FROM REGISTRY"
		except Exception,e:
			print "FREESTEAM REGISTRY KEY NOT FOUND (%s)" % str(e)
			pass # Couldn't find the key, just act like we can't read the registry
		env.Append(LIBPATH=[os.path.join(prefix,"lib")])
		env.Append(CPPPATH=[os.path.join(prefix,"include")])
	else:
		print "Error: unable to read Windows registry!"
		sys.exit(1)
else:
	env.ParseConfig(['freesteam-config','--libs','--cppflags'])

env.Program('example.cpp',LIBS=['freesteam']);
env.Program('dens_ph.cpp',LIBS=['freesteam']);

