#!/usr/bin/env python
Import('env')

envg = env.Clone()

envg.ParseConfig('pkg-config gtk+-2.0 --libs --cflags')

conf = envg.Configure()
if not conf.CheckHeader('gtk/gtk.h'):
	print("Unable to build GTK GUI: GTK header not found.")
else:
	envg['GTK_GLADE_FILE'] = "freesteam-gtk.glade"

	envg.Append(
		LIBPATH=["#"]
		,LIBS=['freesteam']
		,CPPPATH=['#']
		,CPPDEFINES={
			"GTK_GLADE_DIR":"\\\"${GTK_GLADE_DIR}\\\""
			,"GTK_GLADE_FILE":"\\\"${GTK_GLADE_FILE}\\\""		
			,'FREESTEAM_LOCAL':1
		}
	)

	prog = envg.Program("freesteam-gtk",['freesteam-gtk.c','callbacks.c'])

	print("$INSTALL_BIN = ",env.subst('$INSTALL_BIN'))
	envg.Install("$GTK_GLADE_DIR",["$GTK_GLADE_FILE","icon.png"])
	envg.Install("$INSTALL_BIN", prog)
	
#	env['installedfiles'] += [env.Install("${INSTALL_ROOT}${GTK_GLADE_DIR}",["${GTK_GLADE_FILE}"])]
#	env['installedfiles'] += [env.Install("${INSTALL_ROOT}${GTK_GLADE_DIR}",["icon.png"])]
#	env['installedfiles'] += [env.Install("${INSTALL_ROOT}$INSTALL_BIN",[prog])]

# vim:set ts=4 sw=4 noexpandtab ft=python:
