#!/usr/bin/env python
Import('env')

if env.get('HAVE_GTK'):

	gtk_env = env.Clone()

	gtk_env.Append(
		LIBPATH=["#"]+env.get('GTK_LIBPATH')
		,LIBS=['freesteam'] + env.get('GTK_LIBS')
		,CPPPATH=['#',env.get('GTK_CPPPATH')]
		,CPPDEFINES=['FREESTEAM_LOCAL']
	)

	gtk_env.Program("freesteam-gtk",['freesteam-gtk.c','callbacks.c'])


