# simple SCons script to build the example(s)

import platform, os
tools = ['default']
ENV = {"PATH":os.environ['PATH']}
if platform.system() == "Windows":
	tools = ['mingw']
	ENV = os.environ

env = Environment(tools=tools,ENV=ENV)
import sys

if platform.system() == "Windows":
	# windows has problems, so we help it along a bit...
	cmd = [sys.executable,r'..\freesteam-config']
else:
	# on other platforms, it just works...
	cmd = ['freesteam-config']

env.ParseConfig(cmd + ['--libs','--cppflags'])
	
env.Program('isentropic',['isentropic.c'])

