freesteam: Boundaries Class Reference
Boundaries Class Reference
#include <boundaries.h>
Static Public Member Functions
static bool isValid_pT (Pressure p, Temperature T, bool throw_me=false)
Overall pressure/temperature validity check.
static bool isRegion1_pT (Pressure p, Temperature T, bool throw_me=false)
Check for a pressure/temperature being in the saturated zone (within some tolerance).
static bool isRegion2_pT (Pressure p, Temperature T, bool throw_me=false)
Test for a pressure/temperature being in Region 2.
static bool isRegion3_pT (Pressure p, Temperature T, bool throw_me=false)
Test for a pressure/temperutare being in Region 3.
static bool isBound_pT (Pressure p, Temperature T, bool throw_me=false)
static bool isSat_Tx (const Temperature &T, const Num &x, const bool throw_me=false)
static Pressure getSatPres_T (Temperature T)
Get the saturation pressure for a specific temperature.
static Temperature getSatTemp_p (Pressure p)
Get the saturation temperature for a specific pressure.
static Density getSatDensWater_T (const Temperature &T)
static Density getSatDensSteam_T (const Temperature &T)
static Pressure getpbound_T (Temperature T, bool throw_me=false)
static Temperature getTbound_p (Pressure p, bool throw_me=false)
Member Function Documentation
bool Boundaries::isValid_pT (Pressure p, Temperature T, bool throw_me = false) [static]
Overall pressure/temperature validity check.
Check that the pressure and temperature are within limits, and optionally throw an error if they are out of bounds.
References P_MAX, P_MIN, STEAM_P_EPS, STEAM_T_EPS, STM_PRESSURE_HIGH, STM_PRESSURE_LOW, STM_TEMPERATURE_HIGH, STM_TEMPERATURE_LOW, T_MAX, and T_MIN.
Referenced by isRegion1_pT(), isRegion2_pT(), isRegion3_pT(), and SteamCalculator::isValid().
bool Boundaries::isRegion1_pT (Pressure p, Temperature T, bool throw_me = false) [static]
Check for a pressure/temperature being in the saturated zone (within some tolerance).
Check that the temperature and pressure given indicate saturated conditions.
Note that the STM_SATURATION_TOL is used to allow a small region of error on this test.
Parameters:
p pressure / [MPa]
T temperature / [K] Test for a pressure/temperature being in Region 1
p pressure / [MPa]
T temperature / [K]]
throw_me Throw an error if point is not in Region 1
References getSatPres_T(), isValid_pT(), REG1_RANGE_P_LOW, REG1_RANGE_T_HIGH, and T_REG1_REG3.
Referenced by SteamCalculator::setRegion1_pT().
bool Boundaries::isRegion2_pT (Pressure p, Temperature T, bool throw_me = false) [static]
Test for a pressure/temperature being in Region 2.
Parameters:
p pressure / [MPa]
T temperature / [K]]
throw_me Throw an error if point is not in Region 2
References getpbound_T(), getSatPres_T(), isValid_pT(), REG2_RANGE_P_HIGH_PB, REG2_RANGE_T_LOW_TS, T_REG1_REG3, and TB_HIGH.
Referenced by SteamCalculator::setRegion2_pT().
bool Boundaries::isRegion3_pT (Pressure p, Temperature T, bool throw_me = false) [static]
Test for a pressure/temperutare being in Region 3.
Parameters:
p pressure / [MPa]
T temperature / [K]]
throw_me Throw an error if point is not in Region 3
References getpbound_T(), isValid_pT(), REG3_RANGE_P_LOW_PB, REG3_RANGE_T_LOW_TB, and T_REG1_REG3.
static bool Boundaries::isBound_pT (Pressure p, Temperature T, bool throw_me = false) [static]
bool Boundaries::isSat_Tx (const Temperature & T, const Num & x, const bool throw_me = false) [static]
References isnan(), T_CRIT, and T_TRIPLE.
Referenced by SteamCalculator::setRegion4_Tx().
Pressure Boundaries::getSatPres_T (Temperature T) [static]
Get the saturation pressure for a specific temperature.
This the 'Basic equation' for Region 4,
See also:
IF-97 p 33
References IAPWS95::a, IAPWS95::b, IAPWS95::c, MPa, pow(), REQUIRE, sq(), T_MIN, and TB_LOW.
Referenced by isRegion1_pT(), isRegion2_pT(), SteamCalculator::set_pT(), SteamCalculator::setSatSteam_T(), SteamCalculator::setSatWater_T(), and SteamCalculator::whichState().
Temperature Boundaries::getSatTemp_p (Pressure p) [static]
Get the saturation temperature for a specific pressure.
This is based on the 'Backward equation' for Region 4
See also:
IF-97 p 34
References IAPWS95::b, IAPWS95::d, Kelvin, REGION4_N, and sq().
Referenced by SteamCalculator::setSatSteam_p(), and SteamCalculator::setSatWater_p().
Density Boundaries::getSatDensWater_T (const Temperature & T) [static]
See also:
http://www.iapws.org/relguide/supsat.pdf
Todo:
Limit getSatDensWater_T from being called with T <= TB_LOW
References ENSURE, isnan(), pow(), REGION43_B, REQUIRE, RHO_CRIT, sq(), T_CRIT, and T_TRIPLE.
Referenced by SteamCalculator::setSatWater_T(), and SteamCalculator::whichState().
Density Boundaries::getSatDensSteam_T (const Temperature & T) [static]
See also:
http://www.iapws.org/relguide/supsat.pdf
Todo:
Limit getSatDensSteam_T from being called with T <= TB_LOW
References pow(), REGION43_C, REQUIRE, RHO_CRIT, sq(), T_CRIT, and T_TRIPLE.
Referenced by SteamCalculator::set_pT(), SteamCalculator::setSatSteam_T(), and SteamCalculator::whichState().
Pressure Boundaries::getpbound_T (Temperature T, bool throw_me = false) [static]
References B23_N, Kelvin, MPa, REG2_RANGE_TB_HIGH, REG2_RANGE_TB_LOW, sq(), T_REG1_REG3, and TB_HIGH.
Referenced by isRegion2_pT(), isRegion3_pT(), SteamCalculator::set_pT(), Region3::set_pT(), SteamCalculator::setB23_T(), and SteamCalculator::whichState().
Temperature Boundaries::getTbound_p (Pressure p, bool throw_me = false) [static]
References B23_N, Kelvin, MPa, PB_LOW, pow(), REG2_P_HIGH, REG2_RANGE_PB_HIGH, and REG2_RANGE_PB_LOW.
Referenced by SteamCalculator::setB23_p().
The documentation for this class was generated from the following files:
boundaries.h
boundaries.cpp