freesteam: SteamState Class Reference
SteamState Class Reference
#include <state.h>
Public Member Functions
virtual int getRegion (void) const
virtual SpecificVolume specvol (const SteamCalculator &c) const =0
virtual SpecificEnergy specienergy (const SteamCalculator &c) const =0
virtual SpecificEntropy specentropy (const SteamCalculator &c) const =0
virtual SpecificEnergy specenthalpy (const SteamCalculator &c) const =0
virtual SpecHeatCap speccp (const SteamCalculator &c) const =0
virtual SpecHeatCap speccv (const SteamCalculator &c) const =0
virtual Temperature temp (const SteamCalculator &c) const =0
virtual Pressure pres (const SteamCalculator &c) const =0
virtual Density dens (const SteamCalculator &c) const =0
Protected Member Functions
virtual void set_pT (SteamCalculator &c, const Pressure &p, const Temperature &T, Num x=-1)=0
virtual Num pitau_iaps85 (const SteamCalculator &c) const =0
virtual Num delpi_iaps85 (const SteamCalculator &c) const =0
SteamState ()
Static Protected Member Functions
static SteamState * Instance ()
Friends
class SteamCalculator
Constructor & Destructor Documentation
SteamState::SteamState () [inline, protected]
Member Function Documentation
int SteamState::getRegion (void) const [virtual]
Reimplemented in Region1, Region2, Region3, and Region4.
Referenced by SteamCalculator::set_pT(), and SteamCalculator::whichRegion().
virtual SpecificVolume SteamState::specvol (const SteamCalculator & c) const [pure virtual]
Implemented in Region1, Region2, Region3, and Region4.
Referenced by SteamCalculator::specvol().
virtual SpecificEnergy SteamState::specienergy (const SteamCalculator & c) const [pure virtual]
Implemented in Region1, Region2, Region3, and Region4.
Referenced by SteamCalculator::specienergy().
virtual SpecificEntropy SteamState::specentropy (const SteamCalculator & c) const [pure virtual]
Implemented in Region1, Region2, Region3, and Region4.
Referenced by SteamCalculator::specentropy().
virtual SpecificEnergy SteamState::specenthalpy (const SteamCalculator & c) const [pure virtual]
Implemented in Region1, Region2, Region3, and Region4.
Referenced by SteamCalculator::specenthalpy().
virtual SpecHeatCap SteamState::speccp (const SteamCalculator & c) const [pure virtual]
Implemented in Region1, Region2, Region3, and Region4.
Referenced by SteamCalculator::speccp().
virtual SpecHeatCap SteamState::speccv (const SteamCalculator & c) const [pure virtual]
Implemented in Region1, Region2, Region3, and Region4.
Referenced by SteamCalculator::speccv().
virtual Temperature SteamState::temp (const SteamCalculator & c) const [pure virtual]
Implemented in Region1, Region2, Region3, and Region4.
Referenced by SteamCalculator::temp().
virtual Pressure SteamState::pres (const SteamCalculator & c) const [pure virtual]
Implemented in Region1, Region2, Region3, and Region4.
Referenced by SteamCalculator::getRegion3PressureError(), and SteamCalculator::pres().
virtual Density SteamState::dens (const SteamCalculator & c) const [pure virtual]
Implemented in Region1, Region2, Region3, and Region4.
Referenced by SteamCalculator::dens().
static SteamState* SteamState::Instance () [static, protected]
Reimplemented in Region1, Region2, Region3, and Region4.
virtual void SteamState::set_pT (SteamCalculator & c, const Pressure & p, const Temperature & T, Num x = -1) [protected, pure virtual]
Implemented in Region1, Region2, Region3, and Region4.
Referenced by SteamCalculator::set_pT(), SteamCalculator::setB23_p(), SteamCalculator::setB23_T(), SteamCalculator::setRegion1_pT(), SteamCalculator::setRegion2_pT(), SteamCalculator::setSatSteam_p(), SteamCalculator::setSatSteam_T(), SteamCalculator::setSatWater_p(), and SteamCalculator::setSatWater_T().
virtual Num SteamState::pitau_iaps85 (const SteamCalculator & c) const [protected, pure virtual]
Implemented in Region4.
Referenced by SteamCalculator::pitau_iaps85().
virtual Num SteamState::delpi_iaps85 (const SteamCalculator & c) const [protected, pure virtual]
Implemented in Region4.
Referenced by SteamCalculator::delpi_iaps85().
Friends And Related Function Documentation
friend class SteamCalculator [friend]
Reimplemented in Region1, Region2, Region3, and Region4.
The documentation for this class was generated from the following files:
state.h
state.cpp