freesteam: SatCurve< Ordinate, Temperature, OrdinateAlt, 0 > Class Template Reference
SatCurve< Ordinate, Temperature, OrdinateAlt, 0 > Class Template Reference
SatCurve for case where Abscissa is temperature.
#include <satcurve.h>
Public Member Functions
SatCurve ()
virtual ~SatCurve ()
virtual Ordinate solve (const Temperature &T, const int &flags=SAT_WATER)
Detailed Description
template<class Ordinate, int OrdinateAlt>
class SatCurve< Ordinate, Temperature, OrdinateAlt, 0 >
SatCurve for case where Abscissa is temperature.
Use p_sat(T) directly then return Ordinate(p_sat,T)
Constructor & Destructor Documentation
template<class Ordinate, int OrdinateAlt> SatCurve< Ordinate, Temperature, OrdinateAlt, 0 >::SatCurve () [inline]
template<class Ordinate, int OrdinateAlt> virtual SatCurve< Ordinate, Temperature, OrdinateAlt, 0 >::~SatCurve () [inline, virtual]
Member Function Documentation
template<class Ordinate, int OrdinateAlt> virtual Ordinate SatCurve< Ordinate, Temperature, OrdinateAlt, 0 >::solve (const Temperature & T, const int & flags = SAT_WATER) [inline, virtual]
References SatCurveBase< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::getOrdinate(), SAT_STEAM, SteamCalculator::setSatSteam_T(), and SteamCalculator::setSatWater_T().
The documentation for this class was generated from the following file:
satcurve.h