freesteam: B23Curve< Ordinate, Abscissa, OrdinateAlternative, AbscissaAlternative > Class Template Reference
B23Curve< Ordinate, Abscissa, OrdinateAlternative, AbscissaAlternative > Class Template Reference
B23 Curve for case where Abscissa is neither temperature nor pressure.
#include <b23curve.h>
Public Member Functions
B23Curve ()
virtual ~B23Curve ()
Ordinate solve (const Abscissa &target)
Friends
class ZeroIn< B23Curve, Temperature, Abscissa >
Detailed Description
template<class Ordinate, class Abscissa, int OrdinateAlternative = 0, int AbscissaAlternative = 0>
class B23Curve< Ordinate, Abscissa, OrdinateAlternative, AbscissaAlternative >
B23 Curve for case where Abscissa is neither temperature nor pressure.
Use a root solving process to first find T where Abscissa(p_sat(T),T) = target
Examples:
/home/john/freesteam/b23curve.h.
Constructor & Destructor Documentation
template<class Ordinate, class Abscissa, int OrdinateAlternative = 0, int AbscissaAlternative = 0> B23Curve< Ordinate, Abscissa, OrdinateAlternative, AbscissaAlternative >::B23Curve () [inline]
template<class Ordinate, class Abscissa, int OrdinateAlternative = 0, int AbscissaAlternative = 0> virtual B23Curve< Ordinate, Abscissa, OrdinateAlternative, AbscissaAlternative >::~B23Curve () [inline, virtual]
Member Function Documentation
template<class Ordinate, class Abscissa, int OrdinateAlternative = 0, int AbscissaAlternative = 0> Ordinate B23Curve< Ordinate, Abscissa, OrdinateAlternative, AbscissaAlternative >::solve (const Abscissa & target) [inline, virtual]
Implements B23CurveBase< Ordinate, Abscissa, OrdinateAlternative, AbscissaAlternative >.
References fabs(), ZeroIn< Subject, Ordinate, Abscissa >::getError(), B23CurveBase< Ordinate, Abscissa, OrdinateAlternative, AbscissaAlternative >::getOrdinate(), ZeroIn< Subject, Ordinate, Abscissa >::getSolution(), ZeroIn< Subject, Ordinate, Abscissa >::isSolved(), Kelvin, Percent, SteamCalculator::setB23_T(), ZeroIn< Subject, Ordinate, Abscissa >::setLowerBound(), ZeroIn< Subject, Ordinate, Abscissa >::setMethod(), ZeroIn< Subject, Ordinate, Abscissa >::setTolerance(), ZeroIn< Subject, Ordinate, Abscissa >::setUpperBound(), TB_HIGH, TB_LOW, and ZeroIn< Subject, Ordinate, Abscissa >::visit().
Referenced by freesteam_region_ph(), and Solver2< FirstProp, SecondProp, FirstPropAlt, SecondPropAlt >::whichRegion().
Friends And Related Function Documentation
template<class Ordinate, class Abscissa, int OrdinateAlternative = 0, int AbscissaAlternative = 0> friend class ZeroIn< B23Curve, Temperature, Abscissa > [friend]
The documentation for this class was generated from the following file:
b23curve.h