freesteam: Region1 Class Reference
Region1 Class Reference
#include <region1.h>
Protected Member Functions
virtual SpecificVolume specvol (const SteamCalculator &c) const
virtual SpecificEnergy specienergy (const SteamCalculator &c) const
virtual SpecificEntropy specentropy (const SteamCalculator &c) const
virtual SpecificEnergy specenthalpy (const SteamCalculator &c) const
virtual SpecHeatCap speccp (const SteamCalculator &c) const
virtual SpecHeatCap speccv (const SteamCalculator &c) const
virtual Temperature temp (const SteamCalculator &c) const
virtual Pressure pres (const SteamCalculator &c) const
virtual Density dens (const SteamCalculator &c) const
int getRegion () const
virtual void set_pT (SteamCalculator &c, const Pressure &p, const Temperature &T, Num x)
Static Protected Member Functions
static SteamState * Instance ()
Friends
class SteamCalculator
class Region4
Member Function Documentation
SpecificVolume Region1::specvol (const SteamCalculator & c) const [inline, protected, virtual]
Returns:
Specific volume of steam [m³/kg]
Implements SteamState.
References SteamCalculator::p, SteamCalculator::pi, R, and SteamCalculator::T.
Referenced by dens().
SpecificEnergy Region1::specienergy (const SteamCalculator & c) const [protected, virtual]
Returns:
Specific internal energy of water/steam [kJ/kg]
Implements SteamState.
References SteamCalculator::pi, R, SteamCalculator::T, and SteamCalculator::tau.
SpecificEntropy Region1::specentropy (const SteamCalculator & c) const [protected, virtual]
Returns:
Specific entropy water/steam [kJ/kg]
Implements SteamState.
References R, and SteamCalculator::tau.
SpecificEnergy Region1::specenthalpy (const SteamCalculator & c) const [protected, virtual]
Returns:
Specific enthalpy of water/steam [kJ/kg]
Implements SteamState.
References R, SteamCalculator::T, and SteamCalculator::tau.
SpecHeatCap Region1::speccp (const SteamCalculator & c) const [protected, virtual]
Returns:
Isobaric specific heat capacity of water/steam [kJ/kgK]
Implements SteamState.
References R, sq(), and SteamCalculator::tau.
SpecHeatCap Region1::speccv (const SteamCalculator & c) const [protected, virtual]
Returns:
Isochoric specific heat capacity of water/steam [kJ/kgK]
Implements SteamState.
References R, sq(), and SteamCalculator::tau.
Temperature Region1::temp (const SteamCalculator & c) const [inline, protected, virtual]
Returns:
Temperature of water/steam [K]
Implements SteamState.
References Kelvin, REQUIRE, and SteamCalculator::T.
Pressure Region1::pres (const SteamCalculator & c) const [inline, protected, virtual]
Returns:
Pressure of steam/water[MPa]
Implements SteamState.
References MPa, SteamCalculator::p, and REQUIRE.
Density Region1::dens (const SteamCalculator & c) const [inline, protected, virtual]
Returns:
Density of steam [kg/m³]
Implements SteamState.
References specvol().
SteamState * Region1::Instance () [static, protected]
Reimplemented from SteamState.
Referenced by SteamCalculator::set_pT(), SteamCalculator::setRegion1_pT(), SteamCalculator::setSatWater_p(), and SteamCalculator::setSatWater_T().
int Region1::getRegion (void) const [protected, virtual]
Reimplemented from SteamState.
void Region1::set_pT (SteamCalculator & c, const Pressure & p, const Temperature & T, Num x) [protected, virtual]
Implements SteamState.
References ENSURE, SteamCalculator::isset, SteamCalculator::p, SteamCalculator::pi, REG1_PRES_REF, REG1_TEMP_REF, SteamCalculator::T, SteamCalculator::tau, SteamCalculator::whichRegion(), and SteamCalculator::x.
Friends And Related Function Documentation
friend class SteamCalculator [friend]
Reimplemented from SteamState.
friend class Region4 [friend]
The documentation for this class was generated from the following files:
region1.h
region1.cpp