freesteam: SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt > Class Template Reference
SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt > Class Template Reference
#include <satcurve.h>
Public Member Functions
virtual ~SatCurve ()
Ordinate solve (const Abscissa &target, const int &flags=SAT_WATER)
Static Public Member Functions
static Temperature getLowerBound (const int &flags)
static Temperature getUpperBound (const int &flags)
Friends
class ZeroIn< SatCurve, Temperature, Abscissa >
Detailed Description
template<class Ordinate, class Abscissa, int OrdinateAlt = 0, int AbscissaAlt = 0>
class SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >
Examples:
/home/john/freesteam/satcurve.h.
Constructor & Destructor Documentation
template<class Ordinate, class Abscissa, int OrdinateAlt = 0, int AbscissaAlt = 0> virtual SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::~SatCurve () [inline, virtual]
Member Function Documentation
template<class Ordinate, class Abscissa, int OrdinateAlt = 0, int AbscissaAlt = 0> static Temperature SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::getLowerBound (const int & flags) [inline, static]
References T_TRIPLE.
Referenced by SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::solve().
template<class Ordinate, class Abscissa, int OrdinateAlt = 0, int AbscissaAlt = 0> static Temperature SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::getUpperBound (const int & flags) [inline, static]
References T_CRIT.
Referenced by SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::solve().
template<class Ordinate, class Abscissa, int OrdinateAlt = 0, int AbscissaAlt = 0> Ordinate SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::solve (const Abscissa & target, const int & flags = SAT_WATER) [inline, virtual]
Parameters:
target Value of the Abscissa variable which is sought
flags SAT_WATER or SAT_STEAM
Returns:
the value of the Ordinate variable for saturated steam/water where the Abscissa fulfil the target value.
Note that this function will not solve for T < 3.984°C so you will get some errors there
Implements SatCurveBase< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >.
References fabs(), ZeroIn< Subject, Ordinate, Abscissa >::getError(), SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::getLowerBound(), SatCurveBase< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::getOrdinate(), ZeroIn< Subject, Ordinate, Abscissa >::getSolution(), SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::getUpperBound(), ZeroIn< Subject, Ordinate, Abscissa >::isSolved(), Kelvin, SteamProperty< Property, PropertyAlternative >::name(), Percent, SAT_STEAM, ZeroIn< Subject, Ordinate, Abscissa >::setLowerBound(), ZeroIn< Subject, Ordinate, Abscissa >::setMethod(), SteamCalculator::setSatSteam_T(), SteamCalculator::setSatWater_T(), ZeroIn< Subject, Ordinate, Abscissa >::setTolerance(), ZeroIn< Subject, Ordinate, Abscissa >::setUpperBound(), and ZeroIn< Subject, Ordinate, Abscissa >::visit().
Referenced by freesteam_region_ph(), and Solver2< FirstProp, SecondProp, FirstPropAlt, SecondPropAlt >::whichRegion().
Friends And Related Function Documentation
template<class Ordinate, class Abscissa, int OrdinateAlt = 0, int AbscissaAlt = 0> friend class ZeroIn< SatCurve, Temperature, Abscissa > [friend]
The documentation for this class was generated from the following file:
satcurve.h