freesteam: SteamProperty< Property, PropertyAlternative > Class Template Reference
SteamProperty< Property, PropertyAlternative > Class Template Reference
Return a particular property of steam in the given state.
#include <steamproperty.h>
Public Member Functions
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
const char * name ()
template<>
SpecificEnergy get (const SteamCalculator &S)
template<>
SpecificEnergy get (const SteamCalculator &S)
template<>
Density get (const SteamCalculator &S)
template<>
SpecificVolume get (const SteamCalculator &S)
template<>
Temperature get (const SteamCalculator &S)
template<>
Pressure get (const SteamCalculator &S)
template<>
SpecificEntropy get (const SteamCalculator &S)
template<>
SpecHeatCap get (const SteamCalculator &S)
template<>
SpecHeatCap get (const SteamCalculator &S)
template<>
Num get (const SteamCalculator &S)
template<>
const bool plotOnLogAxis ()
template<>
const bool plotOnLogAxis ()
Static Public Member Functions
static Property get (const SteamCalculator &S)
static const char * name ()
static const bool plotOnLogAxis ()
Detailed Description
template<class Property, int PropertyAlternative = 0>
class SteamProperty< Property, PropertyAlternative >
Return a particular property of steam in the given state.
Allow evaluation of a desired steam property using template parameters. This is basicaly for internal use, but you may find it useful in your own code, perhaps.
See also:
SatCurve, B23Curve, B13Curve, Solver, Solver2
Member Function Documentation
template<class Property, int PropertyAlternative = 0> static Property SteamProperty< Property, PropertyAlternative >::get (const SteamCalculator & S) [inline, static]
Referenced by SatCurveBase< Ordinate, Units, OrdinateAlt, 0 >::getAbscissa(), B23CurveBase< Ordinate, Units, OrdinateAlternative, 0 >::getAbscissa(), B13CurveBase< Ordinate, Units, OrdinateAlt, 0 >::getAbscissa(), SolverBase< Units, OtherProp, Units, 0, OtherPropAlt, 0 >::getError_vp(), Solver2Base< FirstProp, SecondProp, FirstPropAlt, SecondPropAlt >::getFirstProp(), SatCurveBase< Ordinate, Units, OrdinateAlt, 0 >::getOrdinate(), B23CurveBase< Ordinate, Units, OrdinateAlternative, 0 >::getOrdinate(), B13CurveBase< Ordinate, Units, OrdinateAlt, 0 >::getOrdinate(), Solver2Base< FirstProp, SecondProp, FirstPropAlt, SecondPropAlt >::getSecondProp(), and Solver2< FirstProp, SecondProp, FirstPropAlt, SecondPropAlt >::solve().
template<class Property, int PropertyAlternative = 0> static const char* SteamProperty< Property, PropertyAlternative >::name () [static]
Referenced by Solver2< FirstProp, SecondProp, FirstPropAlt, SecondPropAlt >::solve(), SolverBase< Units, OtherProp, Units, 0, OtherPropAlt, 0 >::solve(), SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::solve(), and B13Curve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::solve().
template<class Property, int PropertyAlternative = 0> static const bool SteamProperty< Property, PropertyAlternative >::plotOnLogAxis () [inline, static]
template<> const char * SteamProperty< SpecificEnergy, SOLVE_IENERGY >::name () [inline]
template<> const char * SteamProperty< SpecificEnergy, SOLVE_ENTHALPY >::name () [inline]
template<> const char * SteamProperty< Density, 0 >::name () [inline]
template<> const char * SteamProperty< SpecificVolume, 0 >::name () [inline]
template<> const char * SteamProperty< Temperature, 0 >::name () [inline]
template<> const char * SteamProperty< Pressure, 0 >::name () [inline]
template<> const char * SteamProperty< SpecificEntropy, SOLVE_ENTROPY >::name () [inline]
template<> const char * SteamProperty< SpecHeatCap, SOLVE_CP >::name () [inline]
template<> const char * SteamProperty< SpecHeatCap, SOLVE_CV >::name () [inline]
template<> const char * SteamProperty< Num, 0 >::name () [inline]
template<> const char * SteamProperty< SpecificEnergy, SOLVE_IENERGY >::name () [inline]
template<> const char * SteamProperty< SpecificEnergy, SOLVE_ENTHALPY >::name () [inline]
template<> const char * SteamProperty< Density, 0 >::name () [inline]
template<> const char * SteamProperty< SpecificVolume, 0 >::name () [inline]
template<> const char * SteamProperty< Temperature, 0 >::name () [inline]
template<> const char * SteamProperty< Pressure, 0 >::name () [inline]
template<> const char * SteamProperty< SpecificEntropy, SOLVE_ENTROPY >::name () [inline]
template<> const char * SteamProperty< SpecHeatCap, SOLVE_CP >::name () [inline]
template<> const char * SteamProperty< SpecHeatCap, SOLVE_CV >::name () [inline]
template<> const char * SteamProperty< Num, 0 >::name () [inline]
template<> SpecificEnergy SteamProperty< SpecificEnergy, SOLVE_IENERGY >::get (const SteamCalculator & S) [inline]
References SteamCalculator::specienergy().
template<> SpecificEnergy SteamProperty< SpecificEnergy, SOLVE_ENTHALPY >::get (const SteamCalculator & S) [inline]
References SteamCalculator::specenthalpy().
template<> Density SteamProperty< Density, 0 >::get (const SteamCalculator & S) [inline]
References SteamCalculator::dens().
template<> SpecificVolume SteamProperty< SpecificVolume, 0 >::get (const SteamCalculator & S) [inline]
References SteamCalculator::specvol().
template<> Temperature SteamProperty< Temperature, 0 >::get (const SteamCalculator & S) [inline]
References SteamCalculator::temp().
template<> Pressure SteamProperty< Pressure, 0 >::get (const SteamCalculator & S) [inline]
References SteamCalculator::pres().
template<> SpecificEntropy SteamProperty< SpecificEntropy, SOLVE_ENTROPY >::get (const SteamCalculator & S) [inline]
References SteamCalculator::specentropy().
template<> SpecHeatCap SteamProperty< SpecHeatCap, SOLVE_CP >::get (const SteamCalculator & S) [inline]
References SteamCalculator::speccp().
template<> SpecHeatCap SteamProperty< SpecHeatCap, SOLVE_CV >::get (const SteamCalculator & S) [inline]
References SteamCalculator::speccv().
template<> Num SteamProperty< Num, 0 >::get (const SteamCalculator & S) [inline]
References SteamCalculator::quality().
template<> const bool SteamProperty< SpecificVolume, 0 >::plotOnLogAxis () [inline]
template<> const bool SteamProperty< Pressure, 0 >::plotOnLogAxis () [inline]
The documentation for this class was generated from the following file:
steamproperty.h