freesteam: Region4 Class Reference
Region4 Class Reference
#include <region4.h>
Public Member Functions
int getRegion () const
SpecificVolume specvol (const SteamCalculator &c) const
SpecificEnergy specienergy (const SteamCalculator &c) const
SpecificEntropy specentropy (const SteamCalculator &c) const
SpecificEnergy specenthalpy (const SteamCalculator &c) const
SpecHeatCap speccp (const SteamCalculator &c) const
SpecHeatCap speccv (const SteamCalculator &c) const
Density dens (const SteamCalculator &c) const
Pressure pres (const SteamCalculator &c) const
Temperature temp (const SteamCalculator &c) const
Protected Member Functions
virtual void set_pT (SteamCalculator &c, const Pressure &p, const Temperature &T, Num x)
virtual Num pitau_iaps85 (const SteamCalculator &c) const
virtual Num delpi_iaps85 (const SteamCalculator &c) const
Static Protected Member Functions
static SteamState * Instance ()
Friends
class SteamCalculator
Member Function Documentation
int Region4::getRegion (void) const [virtual]
Reimplemented from SteamState.
SpecificVolume Region4::specvol (const SteamCalculator & c) const [virtual]
Implements SteamState.
SpecificEnergy Region4::specienergy (const SteamCalculator & c) const [virtual]
Implements SteamState.
SpecificEntropy Region4::specentropy (const SteamCalculator & c) const [virtual]
Implements SteamState.
SpecificEnergy Region4::specenthalpy (const SteamCalculator & c) const [virtual]
Implements SteamState.
SpecHeatCap Region4::speccp (const SteamCalculator & c) const [virtual]
Implements SteamState.
SpecHeatCap Region4::speccv (const SteamCalculator & c) const [virtual]
Implements SteamState.
Density Region4::dens (const SteamCalculator & c) const [virtual]
Implements SteamState.
References ASSERT, SteamCalculator::dens(), SteamCalculator::gas, SteamCalculator::liq, and SteamCalculator::x.
Pressure Region4::pres (const SteamCalculator & c) const [virtual]
Implements SteamState.
References SteamCalculator::gas, and SteamCalculator::pres().
Temperature Region4::temp (const SteamCalculator & c) const [virtual]
Implements SteamState.
References SteamCalculator::T.
SteamState * Region4::Instance () [static, protected]
Reimplemented from SteamState.
References SteamCalculator::Region4.
Referenced by SteamCalculator::set_pT(), and SteamCalculator::setRegion4_Tx().
void Region4::set_pT (SteamCalculator & c, const Pressure & p, const Temperature & T, Num x) [protected, virtual]
Set properties in region 4
Parameters:
c SteamCalculator object to contain the properties defining the current state
p Pressure (redundant, does nothing)
T Saturation temperature
x Quality
Todo:
Work out a way to do this without using a redundant parameter 'p'
Implements SteamState.
References ENSURE, SteamCalculator::gas, SteamCalculator::isset, SteamCalculator::liq, SteamCalculator::p, SteamCalculator::pres(), REQUIRE, SteamCalculator::setSatSteam_T(), SteamCalculator::setSatWater_T(), SteamCalculator, SteamCalculator::T, SteamCalculator::whichRegion(), and SteamCalculator::x.
Num Region4::pitau_iaps85 (const SteamCalculator & c) const [protected, virtual]
Implements SteamState.
Num Region4::delpi_iaps85 (const SteamCalculator & c) const [protected, virtual]
Implements SteamState.
Friends And Related Function Documentation
friend class SteamCalculator [friend]
Reimplemented from SteamState.
Referenced by set_pT().
The documentation for this class was generated from the following files:
region4.h
region4.cpp