freesteam: Water95 Class Reference
Water95 Class Reference
#include <iapws95.h>
Public Member Functions
Water95 ()
~Water95 ()
Num p (const Num &T, const Num &rho)
Num u (const Num &T, const Num &rho)
Num h (const Num &T, const Num &rho)
Num s (const Num &T, const Num &rho)
Num cp (const Num &T, const Num &rho)
Num cv (const Num &T, const Num &rho)
Num w (const Num &T, const Num &rho)
Public Attributes
const Num & R
Universal gas constant, kJ/(kg*K).
const Num & Tc
Water critical temperature, K.
const Num & rhoc
Water critical density, kg/m^3.
Detailed Description
The thermodynamic properties of water calculated with the IAPWS95 equations. Variables and units:
T Temperature, K rho Density, kg/m^3 p Pressure, MPa u Specific internal energy, kJ/kg h Specific enthalpy, kJ/kg s Specific entropy, kJ/(kg*K) cv Isochoric specific heat, kJ/(kg*K) cp Isobaric specific heat, kJ/(kg*K) w Speed of sound, m/s
References:
[1] The International Association for the Properties of Water and Steam, "Release on the IAPWS Formulation 1995 for the Thermodynamic Properties of Ordinary Water Substance for General and Scientific Use", dated September 1996, Fredericia, Denmark. See the "Releases" section of the website http://www.iapws.org/.
[2] NIST Chemistry Webbook: http://webbook.nist.gov/chemistry/fluid/
Constructor & Destructor Documentation
Water95::Water95 ()
Water95::~Water95 () [inline]
Member Function Documentation
Num Water95::p (const Num & T, const Num & rho)
References IAPWS95::get_delta_tau(), IAPWS95::phirdelta(), and R.
Num Water95::u (const Num & T, const Num & rho)
References IAPWS95::get_delta_tau(), IAPWS95::phi0tau(), IAPWS95::phirtau(), and R.
Num Water95::h (const Num & T, const Num & rho)
References IAPWS95::get_delta_tau(), IAPWS95::phi0tau(), IAPWS95::phirdelta(), IAPWS95::phirtau(), and R.
Num Water95::s (const Num & T, const Num & rho)
References IAPWS95::get_delta_tau(), IAPWS95::phi0(), IAPWS95::phi0tau(), IAPWS95::phir(), IAPWS95::phirtau(), and R.
Num Water95::cp (const Num & T, const Num & rho)
References IAPWS95::get_delta_tau(), IAPWS95::phi0tautau(), IAPWS95::phirdelta(), IAPWS95::phirdeltadelta(), IAPWS95::phirdeltatau(), IAPWS95::phirtautau(), and R.
Num Water95::cv (const Num & T, const Num & rho)
References IAPWS95::get_delta_tau(), IAPWS95::phi0tautau(), IAPWS95::phirtautau(), and R.
Num Water95::w (const Num & T, const Num & rho)
References IAPWS95::get_delta_tau(), IAPWS95::phi0tautau(), IAPWS95::phirdelta(), IAPWS95::phirdeltadelta(), IAPWS95::phirdeltatau(), IAPWS95::phirtautau(), and R.
Member Data Documentation
const Num& Water95::R
Universal gas constant, kJ/(kg*K).
Referenced by cp(), cv(), h(), p(), s(), u(), and w().
const Num& Water95::Tc
Water critical temperature, K.
const Num& Water95::rhoc
Water critical density, kg/m^3.
The documentation for this class was generated from the following files:
iapws95.h
iapws95.cpp