freesteam: ConvergenceTest< Property, PropertyAlternative > Class Template Reference
ConvergenceTest< Property, PropertyAlternative > Class Template Reference
#include <convergencetest.h>
Public Member Functions
template<>
bool test (const SpecificEnergy &error, const Pressure &p, const Temperature &T)
template<>
bool test (const SpecificEnergy &error, const Pressure &p, const Temperature &T)
template<>
bool test (const Density &error, const Pressure &p, const Temperature &T)
template<>
bool test (const SpecificVolume &error, const Pressure &p, const Temperature &T)
template<>
bool test (const Pressure &error, const Pressure &p, const Temperature &T)
template<>
bool test (const Temperature &error, const Pressure &p, const Temperature &T)
template<>
bool test (const SpecificEntropy &error, const Pressure &p, const Temperature &T)
template<>
bool test (const SpecHeatCap &error, const Pressure &p, const Temperature &T)
template<>
bool test (const SpecHeatCap &error, const Pressure &p, const Temperature &T)
template<>
bool test (const Num &error, const Pressure &p, const Temperature &T)
template<>
bool test (const SpecificEnergy &error, const Pressure &p, const Temperature &T)
template<>
bool test (const SpecificEnergy &error, const Pressure &p, const Temperature &T)
template<>
bool test (const Density &error, const Pressure &p, const Temperature &T)
template<>
bool test (const SpecificVolume &error, const Pressure &p, const Temperature &T)
template<>
bool test (const Pressure &error, const Pressure &p, const Temperature &T)
template<>
bool test (const Temperature &error, const Pressure &p, const Temperature &T)
template<>
bool test (const SpecificEntropy &error, const Pressure &p, const Temperature &T)
template<>
bool test (const SpecHeatCap &error, const Pressure &p, const Temperature &T)
template<>
bool test (const SpecHeatCap &error, const Pressure &p, const Temperature &T)
template<>
bool test (const Num &error, const Pressure &p, const Temperature &T)
Static Public Member Functions
static bool test (const Property &X, const Pressure &p, const Temperature &T)
template<class Property, int PropertyAlternative = 0>
class ConvergenceTest< Property, PropertyAlternative >
Member Function Documentation
template<class Property, int PropertyAlternative = 0> static bool ConvergenceTest< Property, PropertyAlternative >::test (const Property & X, const Pressure & p, const Temperature & T) [static]
template<> bool ConvergenceTest< SpecificEnergy, SOLVE_IENERGY >::test (const SpecificEnergy & error, const Pressure & p, const Temperature & T) [inline]
References errorU, fabs(), and R.
template<> bool ConvergenceTest< SpecificEnergy, SOLVE_ENTHALPY >::test (const SpecificEnergy & error, const Pressure & p, const Temperature & T) [inline]
References errorH, fabs(), and R.
template<> bool ConvergenceTest< Density, 0 >::test (const Density & error, const Pressure & p, const Temperature & T) [inline]
References errorRHO, fabs(), and R.
template<> bool ConvergenceTest< SpecificVolume, 0 >::test (const SpecificVolume & error, const Pressure & p, const Temperature & T) [inline]
References errorV, fabs(), and R.
template<> bool ConvergenceTest< Pressure, 0 >::test (const Pressure & error, const Pressure & p, const Temperature & T) [inline]
References errorP, and fabs().
template<> bool ConvergenceTest< Temperature, 0 >::test (const Temperature & error, const Pressure & p, const Temperature & T) [inline]
References errorT, and fabs().
template<> bool ConvergenceTest< SpecificEntropy, SOLVE_ENTROPY >::test (const SpecificEntropy & error, const Pressure & p, const Temperature & T) [inline]
References errorS, fabs(), and R.
template<> bool ConvergenceTest< SpecHeatCap, SOLVE_CP >::test (const SpecHeatCap & error, const Pressure & p, const Temperature & T) [inline]
References errorCP, fabs(), and R.
template<> bool ConvergenceTest< SpecHeatCap, SOLVE_CV >::test (const SpecHeatCap & error, const Pressure & p, const Temperature & T) [inline]
References errorCV, fabs(), and R.
template<> bool ConvergenceTest< Num, 0 >::test (const Num & error, const Pressure & p, const Temperature & T) [inline]
References errorX, and fabs().
template<> bool ConvergenceTest< SpecificEnergy, SOLVE_IENERGY >::test (const SpecificEnergy & error, const Pressure & p, const Temperature & T) [inline]
template<> bool ConvergenceTest< SpecificEnergy, SOLVE_ENTHALPY >::test (const SpecificEnergy & error, const Pressure & p, const Temperature & T) [inline]
template<> bool ConvergenceTest< Density, 0 >::test (const Density & error, const Pressure & p, const Temperature & T) [inline]
template<> bool ConvergenceTest< SpecificVolume, 0 >::test (const SpecificVolume & error, const Pressure & p, const Temperature & T) [inline]
template<> bool ConvergenceTest< Pressure, 0 >::test (const Pressure & error, const Pressure & p, const Temperature & T) [inline]
template<> bool ConvergenceTest< Temperature, 0 >::test (const Temperature & error, const Pressure & p, const Temperature & T) [inline]
template<> bool ConvergenceTest< SpecificEntropy, SOLVE_ENTROPY >::test (const SpecificEntropy & error, const Pressure & p, const Temperature & T) [inline]
template<> bool ConvergenceTest< SpecHeatCap, SOLVE_CP >::test (const SpecHeatCap & error, const Pressure & p, const Temperature & T) [inline]
template<> bool ConvergenceTest< SpecHeatCap, SOLVE_CV >::test (const SpecHeatCap & error, const Pressure & p, const Temperature & T) [inline]
template<> bool ConvergenceTest< Num, 0 >::test (const Num & error, const Pressure & p, const Temperature & T) [inline]
The documentation for this class was generated from the following file:
convergencetest.h