freesteam: Region2 Class Reference
Region2 Class Reference
#include <region2.h>
Protected Member Functions
virtual SpecificVolume specvol (const SteamCalculator &c) const
virtual SpecificEnergy specienergy (const SteamCalculator &c) const
virtual SpecificEntropy specentropy (const SteamCalculator &c) const
virtual SpecificEnergy specenthalpy (const SteamCalculator &c) const
virtual SpecHeatCap speccp (const SteamCalculator &c) const
virtual SpecHeatCap speccv (const SteamCalculator &c) const
virtual Temperature temp (const SteamCalculator &c) const
virtual Pressure pres (const SteamCalculator &c) const
virtual Density dens (const SteamCalculator &c) const
int getRegion () const
virtual void set_pT (SteamCalculator &c, const Pressure &p, const Temperature &T, Num x)
Static Protected Member Functions
static SteamState * Instance ()
Friends
class SteamCalculator
class Region4
Member Function Documentation
SpecificVolume Region2::specvol (const SteamCalculator & c) const [inline, protected, virtual]
Returns:
Specific volume of steam [m³/kg]
Implements SteamState.
References SteamCalculator::p, SteamCalculator::pi, R, and SteamCalculator::T.
Referenced by dens().
SpecificEnergy Region2::specienergy (const SteamCalculator & c) const [protected, virtual]
Returns:
Specific internal energy of water/steam [kJ/kg]
Implements SteamState.
References SteamCalculator::pi, R, SteamCalculator::T, and SteamCalculator::tau.
SpecificEntropy Region2::specentropy (const SteamCalculator & c) const [protected, virtual]
Returns:
Specific entropy water/steam [kJ/kg]
Implements SteamState.
References R, and SteamCalculator::tau.
SpecificEnergy Region2::specenthalpy (const SteamCalculator & c) const [protected, virtual]
Returns:
Specific enthalpy of water/steam [kJ/kg]
Implements SteamState.
References R, SteamCalculator::T, and SteamCalculator::tau.
SpecHeatCap Region2::speccp (const SteamCalculator & c) const [protected, virtual]
Returns:
Isobaric specific heat capacity of water/steam [kJ/kgK]
Implements SteamState.
References R, sq(), and SteamCalculator::tau.
SpecHeatCap Region2::speccv (const SteamCalculator & c) const [protected, virtual]
Returns:
Isochoric specific heat capacity of water/steam [kJ/kgK]
Implements SteamState.
References R, sq(), and SteamCalculator::tau.
Temperature Region2::temp (const SteamCalculator & c) const [inline, protected, virtual]
Returns:
Temperature of water/steam [K]
Implements SteamState.
References Kelvin, REQUIRE, and SteamCalculator::T.
Pressure Region2::pres (const SteamCalculator & c) const [inline, protected, virtual]
Returns:
Pressure of steam/water[MPa]
Implements SteamState.
References MPa, SteamCalculator::p, and REQUIRE.
Density Region2::dens (const SteamCalculator & c) const [inline, protected, virtual]
Returns:
Density of steam [kg/m³]
Implements SteamState.
References specvol().
SteamState * Region2::Instance () [static, protected]
Reimplemented from SteamState.
Referenced by SteamCalculator::set_pT(), SteamCalculator::setB23_p(), SteamCalculator::setB23_T(), SteamCalculator::setRegion2_pT(), SteamCalculator::setSatSteam_p(), and SteamCalculator::setSatSteam_T().
int Region2::getRegion (void) const [protected, virtual]
Reimplemented from SteamState.
void Region2::set_pT (SteamCalculator & c, const Pressure & p, const Temperature & T, Num x) [protected, virtual]
Implements SteamState.
References ENSURE, SteamCalculator::isset, MPa, SteamCalculator::p, SteamCalculator::pi, REG2_TEMP_REF, SteamCalculator::T, SteamCalculator::tau, SteamCalculator::whichRegion(), and SteamCalculator::x.
Friends And Related Function Documentation
friend class SteamCalculator [friend]
Reimplemented from SteamState.
friend class Region4 [friend]
The documentation for this class was generated from the following files:
region2.h
region2.cpp