freesteam: Region3 Class Reference
Region3 Class Reference
#include <region3.h>
Public Member Functions
int getRegion () const
SpecificVolume specvol (const SteamCalculator &c) const
SpecificEnergy specienergy (const SteamCalculator &c) const
SpecificEntropy specentropy (const SteamCalculator &c) const
SpecificEnergy specenthalpy (const SteamCalculator &c) const
SpecHeatCap speccp (const SteamCalculator &c) const
SpecHeatCap speccv (const SteamCalculator &c) const
Pressure pres (const SteamCalculator &c) const
Density dens (const SteamCalculator &c) const
Temperature temp (const SteamCalculator &c) const
Protected Member Functions
virtual void set_pT (SteamCalculator &c, const Pressure &p, const Temperature &T, Num x)
Static Protected Member Functions
static SteamState * Instance ()
Friends
class SteamCalculator
Member Function Documentation
int Region3::getRegion (void) const [virtual]
Reimplemented from SteamState.
SpecificVolume Region3::specvol (const SteamCalculator & c) const [virtual]
Implements SteamState.
References SteamCalculator::rho.
SpecificEnergy Region3::specienergy (const SteamCalculator & c) const [virtual]
Implements SteamState.
References R, SteamCalculator::T, and SteamCalculator::tau.
SpecificEntropy Region3::specentropy (const SteamCalculator & c) const [virtual]
Implements SteamState.
References R, and SteamCalculator::tau.
SpecificEnergy Region3::specenthalpy (const SteamCalculator & c) const [virtual]
Implements SteamState.
References SteamCalculator::del, R, SteamCalculator::T, and SteamCalculator::tau.
SpecHeatCap Region3::speccp (const SteamCalculator & c) const [virtual]
Implements SteamState.
References SteamCalculator::del, pow(), R, sq(), and SteamCalculator::tau.
SpecHeatCap Region3::speccv (const SteamCalculator & c) const [virtual]
Implements SteamState.
References R, sq(), and SteamCalculator::tau.
Pressure Region3::pres (const SteamCalculator & c) const [virtual]
Implements SteamState.
References SteamCalculator::del, R, SteamCalculator::rho, and SteamCalculator::T.
Density Region3::dens (const SteamCalculator & c) const [virtual]
Implements SteamState.
References SteamCalculator::rho.
Temperature Region3::temp (const SteamCalculator & c) const [virtual]
Implements SteamState.
References SteamCalculator::T.
SteamState * Region3::Instance () [static, protected]
Reimplemented from SteamState.
Referenced by SteamCalculator::set_pT(), SteamCalculator::setRegion3_rhoT(), and SteamCalculator::setSatWater_p().
void Region3::set_pT (SteamCalculator & c, const Pressure & p, const Temperature & T, Num x) [protected, virtual]
I think this is how this is (vertical lines only approximately vertical)
        ^
        |
  p     |s~5.1                   |T~T13
        |                        |
        |          crit          |
        |           __pt         |              p = P_CRIT
        |       _-''  ''-_       |-------------
        |     .'          '.     |
        |   .'sat        sat'.   |
        |  - vap          liq -  |
        | /                    \ |
        |/                      \|
        +=================================>
                                     rho
Todo:
: remove redundent 'x' from Region3::set_pT function?
Implements SteamState.
References SteamCalculator::dens(), ENSURE, ZeroIn< Subject, Ordinate, Abscissa >::getError(), Boundaries::getpbound_T(), SteamCalculator::getRegion3PressureError(), SteamCalculator::isset, ZeroIn< Subject, Ordinate, Abscissa >::isSolved(), kg_m3, MPa, P_CRIT, Pascal, SteamCalculator::reg3_target_pressure, REG3_TEMP_REF, REG3_ZEROIN_DENS_MAX, REG3_ZEROIN_TOL, RHO_CRIT, SteamCalculator::set_pT(), ZeroIn< Subject, Ordinate, Abscissa >::setLowerBound(), ZeroIn< Subject, Ordinate, Abscissa >::setMethod(), ZeroIn< Subject, Ordinate, Abscissa >::setTolerance(), ZeroIn< Subject, Ordinate, Abscissa >::setUpperBound(), SteamCalculator::T, T_CRIT, SteamCalculator::tau, ZeroIn< Subject, Ordinate, Abscissa >::visit(), SteamCalculator::whichRegion(), and SteamCalculator::x.
Friends And Related Function Documentation
friend class SteamCalculator [friend]
Reimplemented from SteamState.
The documentation for this class was generated from the following files:
region3.h
region3.cpp