freesteam: B13Curve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt > Class Template Reference
B13Curve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt > Class Template Reference
B13 Curve for case where Abscissa is not pressure.
#include <b13curve.h>
Public Member Functions
Ordinate solve (const Abscissa &target)
Detailed Description
template<class Ordinate, class Abscissa, int OrdinateAlt = 0, int AbscissaAlt = 0>
class B13Curve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >
B13 Curve for case where Abscissa is not pressure.
Use a root solving process to first find p where Abscissa(p_b13(T),T) = target
Examples:
/home/john/freesteam/b13curve.h.
Member Function Documentation
template<class Ordinate, class Abscissa, int OrdinateAlt = 0, int AbscissaAlt = 0> Ordinate B13Curve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::solve (const Abscissa & target) [inline, virtual]
Implements B13CurveBase< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >.
References B13CurveBase< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::getOrdinate(), SteamProperty< Property, PropertyAlternative >::name(), Pascal, SolverBase< MainProp, OtherProp, VaryProp, MainPropAlt, OtherPropAlt, VaryPropAlt >::solve(), and T_REG1_REG3.
Referenced by freesteam_region_ph(), and Solver2< FirstProp, SecondProp, FirstPropAlt, SecondPropAlt >::whichRegion().
The documentation for this class was generated from the following file:
b13curve.h