freesteam: MeasurementData Namespace Reference
MeasurementData Namespace Reference
Variables
const double lb = 0.45359237
const double yd = 0.9144
const double in = yd / 36.
const double ft = 12. * in
const double g = 9.80665
const double lbf = lb * g
const double psi = lbf / (in*in)
const double lb_in3 = lb / (in*in*in)
const double Btu = 1055.05585262
Variable Documentation
const double MeasurementData::Btu = 1055.05585262
const double MeasurementData::ft = 12. * in
Referenced by UnitsMapInitialiser::UnitsMapInitialiser().
const double MeasurementData::g = 9.80665
const double MeasurementData::in = yd / 36.
Referenced by UnitsMapInitialiser::UnitsMapInitialiser().
const double MeasurementData::lb = 0.45359237
Referenced by UnitsMapInitialiser::UnitsMapInitialiser().
const double MeasurementData::lb_in3 = lb / (in*in*in)
Referenced by UnitsMapInitialiser::UnitsMapInitialiser().
const double MeasurementData::lbf = lb * g
const double MeasurementData::psi = lbf / (in*in)
Referenced by IAPWS95::phir(), IAPWS95::phirdelta(), IAPWS95::phirdeltadelta(), IAPWS95::phirdeltatau(), IAPWS95::phirtau(), IAPWS95::phirtautau(), and UnitsMapInitialiser::UnitsMapInitialiser().
const double MeasurementData::yd = 0.9144