freesteam: steam.c File Reference
steam.c File Reference
#include "region1.h"
#include "region2.h"
Functions
int freesteam_region_ph (double p, double h)
double freesteam_T_ph (double p, double h)
double freesteam_v_ph (double p, double h)
double freesteam_u_ph (double p, double h)
double freesteam_s_ph (double p, double h)
double freesteam_cp_ph (double p, double h)
double freesteam_cv_ph (double p, double h)
catch (exception &E)
Function Documentation
catch (exception & E)
double freesteam_cp_ph (double p, double h)
double freesteam_cv_ph (double p, double h)
int freesteam_region_ph (double p, double h)
References freesteam_region4_Tsat_p(), SteamCalculator::pres(), RHO_CRIT, SAT_STEAM, SAT_WATER, SteamCalculator::set_pT(), SteamCalculator::setRegion3_rhoT(), SteamCalculator::setSatWater_T(), B23Curve< Ordinate, Abscissa, OrdinateAlternative, AbscissaAlternative >::solve(), B13Curve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::solve(), SatCurve< Ordinate, Abscissa, OrdinateAlt, AbscissaAlt >::solve(), SteamCalculator::specenthalpy(), SteamCalculator::T, T_CRIT, T_MAX, T_REG1_REG3, and T_TRIPLE.
double freesteam_s_ph (double p, double h)
double freesteam_T_ph (double p, double h)
double freesteam_u_ph (double p, double h)
double freesteam_v_ph (double p, double h)