# freesteam - IAPWS-IF97 steam tables library
# Copyright (C) 2004-2005  John Pye
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

Import('env')

env.SharedLibrary('emsofreesteam',['emsohooks.cpp']
	, LIBS = ['freesteam']
	, LIBPATH = '..'
	, CPPDEFINES = 'HAVE_EMSO'
	, CPPPATH = '$EMSO_INCDIR'
)

env.SharedLibrary('emsopipe',['emsopipe.cpp']
	, LIBS = ['freesteam']
	, LIBPATH = '..'
	, CPPDEFINES = 'HAVE_EMSO'
	, CPPPATH = '$EMSO_INCDIR'
)

# From the original makefile...
#   
#   #--------------------------
#   # EMSO integration
#   
#   OBJS = emsohooks.o emsopipe.o
#   
#   EMSO = $(SO_PREFIX)$(EMSO_NAME)$(SO_SUFFIX)
#   EMSOPIPE = $(SO_PREFIX)$(EMSOPIPE_NAME)$(SO_SUFFIX)
#   
#   # Debug flags for EMSO libraries
#   
#   ifdef EMSO_DEBUG
#   	EMSO_DEBUG_FLAG = -DEMSO_DEBUG
#   else
#   	EMSO_DEBUG_FLAG = 
#   endif
#   
#   CPPFLAGS_LOCAL = $(EMSO_DEBUG_FLAG)
#   

#   
#   #-----------------------------------------------------------
#   # INSTALL
#   
#   install: emso
#   ifdef EMSO_INTERFACE_DIR
#   	cp $(EMSO) $(EMSO_INTERFACE_DIR)/$(EMSO);
#   	cp $(EMSOPIPE) $(EMSO_INTERFACE_DIR)/$(EMSOPIPE);
#   else
#   	@echo "Can't install, you need to specify EMSO_INTERFACE_DIR"
#   	exit 1;
#   endif
#   