# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: freesteam MSYS2

on:
  workflow_dispatch:
    branches: [ $default-branch, master]
  push:
    branches: [ $default-branch, master]
  pull_request:
    branches:  [ $default-branch, master]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-gsl
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gtk2
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-wheel
          mingw-w64-x86_64-python-matplotlib

    - uses: actions/checkout@v2

    - name: Install Python dependencies
      run: |
        python3 -m pip install scons


    - name: Build freesteam
      run: |
        mkdir -p ~/.local
        scons INSTALL_PREFIX=~/.local

    - name: Install freesteam
      run: |
        scons INSTALL_PREFIX=~/.local install

    - name: Test freesteam C
      run: |
        scons INSTALL_PREFIX=~/.local test
        export PATH=$PATH:~/.local/bin
        ./test

    - name: Test freesteam Python
      run: |
        export PATH=$PATH:~/.local/bin
        export PYTHONPATH=~/.local/lib/python3.9/site-packages
        cd python
        python3 test.py

# vim: ts=2:sw=2:et

