name: freesteam ubuntu

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch, master ]
  pull_request:
    branches: [ $default-branch, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
 
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgsl-dev scons libgtk2.0-dev swig build-essential texlive-latex-recommended dvipng texlive-latex-extra texlive-fonts-recommended cm-super

    - name: Install 20.04 dependencies
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      run: |
        sudo apt-get install python3-dev python3-matplotlib

    - name: Install 18.04 dependencies
      if: ${{ matrix.os == 'ubuntu-18.04' }}
      run: |
        sudo apt-get install python-dev python-matplotlib

    - name: Build freesteam
      run: |
        mkdir -p ~/.local
        scons PREFIX=~/.local

    - name: Install freesteam
      run: |
        sudo scons PREFIX=~/.local install

    - name: Test freesteam C
      run: |    
        scons PREFIX=~/.local test
        LD_LIBRARY_PATH=. ./test

    - name: Test freesteam python
      run: |
        export LD_LIBRARY_PATH=$PWD
        cd python
        python test.py
        python hsdiagram.py
        python tables.py

# vim: ts=2:sw=2:et
